#################################
#           Animations          #
#################################
animations = true;
animation-stiffness = 180.0; 
animation-dampening = 20.0;
animation-clamping = true;
animation-mass = 1.0;


animation-for-tag-change = "slide-left";

animation-for-open-window = "zoom";
animation-for-unmap-window = "zoom";
animation-for-transient-window = "slide-up";

animation-exclude = [
    "class_g = 'Polybar'",
    "window_type = 'dock'",
    "window_type = 'desktop'"
];

#################################
#           Visuals             #
#################################
corner-radius = 10;
rounded-corners-exclude = [
  "window_type = 'dock'",
  "class_g = 'Polybar'",
  "fullscreen"
];

blur: {
  method = "dual_kawase";
  strength = 5;
  background = true;
}

#################################
#       Backend & Fixes         #
#################################
backend = "glx";
vsync = true;
use-damage = false; # КРИТИЧНО для плавных анимаций в Awesome

wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; }
  dock = { shadow = false; clip-shadow-above = true; }
  dnd = { shadow = false; }
};