# background_image /home/sewaustav/Pictures/wallpapers/NyaITD5-arch-linux-wallpaper.png
# background_image_layout cscaled
# background_tint 0.3
# background_opacity 0.9

font_family JetBrains Mono
font_size 12
enable_audio_bell no
