#! /bin/sh

export GTK_THEME="Adwaita-dark"
export ICON_THEME="Papirus-Dark"
export XCURSOR_THEME="Adwaita"
export XCURSOR_SIZE=24
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
export QT_QPA_PLATFORM=xcb
export XDG_SESSION_TYPE=x11
export DISPLAY=:0

pgrep -x lxappearance > /dev/null || lxappearance 

xsetroot -cursor_name left_ptr &
xrdb -merge ~/.Xresources &

pgrep -x sxhkd > /dev/null || sxhkd &

pgrep -x copyq > /dev/null || copyq &

pgrep -x dunst > /dev/null || dunst &

picom -b &

feh --bg-fill /home/sewaustav/Pictures/wallpapers/japan-fantasy-landscape.jpg &

flameshot &

setxkbmap -layout "us,ru" -option "grp:win_space_toggle" &

pgrep -x polybar > /dev/null || polybar top &

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc rule -a Chromium desktop='^2'