preload = /home/sewaustav/Pictures/wallpapers/wp15331171-arch-linux-4k-wallpapers.jpg

wallpaper {
    monitor = eDP-1
    path = /home/sewaustav/Pictures/wallpapers/wp15331171-arch-linux-4k-wallpapers.jpg
}

splash = false