background {
    path = /home/sewaustav/Pictures/wallpapers/wp14827809-linux-wallpapers.webp
    blur_passes = 3
    contrast = 0.85
    brightness = 0.8
}
input-field {
    size = 350, 60
    outline_thickness = 2
    outline_color = rgba(0, 255, 180, 0.6)
    inner_color = rgba(20, 20, 20, 0.5)
    font_color = rgba(255, 255, 255, 0.9)
    placeholder_text = "Enter password 🔒"
    fade_on_empty = true
    dots_center = true
    position = 0, -120
}
label {
    text = $TIME  # Используй $TIME для 24-часового формата (или $TIME12 для 12-часового с AM/PM)
    font_size = 48
    color = rgba(255, 255, 255, 1.0)  # Добавь цвет, если нужно (по умолчанию белый)
    position = 0, -300
}
label {
    text = cmd[update:1000] date "+%A, %d %B %Y"
    font_size = 20
    color = rgba(255, 255, 255, 1.0)
    position = 0, -250
}
